#!/bin/bash

modprobe greybus
modprobe gb-es2
modprobe gb-gbphy
modprobe gb-i2c
modprobe gb-spi
modprobe gb-gpio
modprobe gb-uart
modprobe configfs
mount -t configfs none /sys/kernel/config
modprobe libcomposite

board=$(sed "s/ /_/g;s/\o0//g" /proc/device-tree/model)

if [ "x${board}" = "xTI_AM335x_PocketBeagle" ] ; then
	modprobe dummy_hcd num=2
	if [ -z "$1" ]
  	then
		mkdir -p /tmp/gbsim0/hotplug-module	
		gbsim -g 0 -h /tmp/gbsim0/ -c 0 -s 1 -i 1
		mkdir -p /tmp/gbsim1/hotplug-module
		gbsim -g 1 -h /tmp/gbsim1/ -c 1 -s 2 -i 2
	else
		if [ "$1" -eq "1" ]
		then	
			mkdir -p /tmp/gbsim0/hotplug-module	
			gbsim -g 0 -h /tmp/gbsim0/ -c 0 -s 1 -i 1
		fi
		if [ "$1" -eq "2" ]
		then	
			mkdir -p /tmp/gbsim1/hotplug-module
			gbsim -g 1 -h /tmp/gbsim1/ -c 1 -s 2 -i 2
		fi	
	fi
else
	modprobe dummy_hcd num=4
	if [ -z "$1" ]
  	then
		mkdir -p /tmp/gbsim0/hotplug-module	
		gbsim -g 0 -h /tmp/gbsim0/ -c 0 -s 2 -i 2
		mkdir -p /tmp/gbsim1/hotplug-module	
		gbsim -g 1 -h /tmp/gbsim1/ -c 1 -s 2 -i 2
		mkdir -p /tmp/gbsim2/hotplug-module	
		gbsim -g 2 -h /tmp/gbsim2/ -c 0 -s 1 -i 2
		mkdir -p /tmp/gbsim3/hotplug-module
		gbsim -g 3 -h /tmp/gbsim3/ -c 0 -s 2 -i 2
	else
		if [ "$1" -eq "1" ]	
		then
			mkdir -p /tmp/gbsim0/hotplug-module	
			gbsim -g 0 -h /tmp/gbsim0/ -c 0 -s 2 -i 2
		fi
		if [ "$1" -eq "2" ]	
		then
			mkdir -p /tmp/gbsim1/hotplug-module	
			gbsim -g 1 -h /tmp/gbsim1/ -c 1 -s 2 -i 2
		fi
		if [ "$1" -eq "3" ]	
		then
			mkdir -p /tmp/gbsim2/hotplug-module	
			gbsim -g 2 -h /tmp/gbsim2/ -c 0 -s 1 -i 2
		fi
		if [ "$1" -eq "4" ]
		then
			mkdir -p /tmp/gbsim3/hotplug-module
			gbsim -g 3 -h /tmp/gbsim3/ -c 0 -s 2 -i 2
		fi
	fi
fi