#!/bin/bash

modprobe greybus
modprobe gb-es2
modprobe gb-gbphy
modprobe gb-i2c
modprobe gb-spi
modprobe gb-gpio
modprobe gb-uart
modprobe configfs
mount -t configfs none /sys/kernel/config
modprobe libcomposite
modprobe dummy_hcd
mkdir -p /tmp/gbsim/hotplug-module
gbsim
